"""SQL 方言 AST 转译 — sqlglot 驱动。

v2-step-09: 替代 Jinja2 字符串拼接,走『解析 → AST 重写 → 重新生成』三步,
实现 MySQL → openGauss/PostgreSQL 的真方言级转换。

典型转换示例:
- DATE_FORMAT(d, '%Y-%m')        → TO_CHAR(d, 'YYYY-MM')
- IFNULL(a, b)                   → COALESCE(a, b)
- GROUP_CONCAT(c SEPARATOR ',')  → STRING_AGG(c, ',')
- JSON_EXTRACT(j, '$.k')         → j -> 'k'
- FROM_UNIXTIME(t)               → TO_TIMESTAMP(t)
- LIMIT N, M                     → LIMIT M OFFSET N
- 反引号标识符                   → 双引号标识符
"""
from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

import sqlglot
from sqlglot.errors import ParseError

log = logging.getLogger(__name__)

_DIALECT_ALIAS = {
    "opengauss":   "postgres",
    "open_gauss":  "postgres",
    "gauss":       "postgres",
    "postgresql":  "postgres",
    "pg":          "postgres",
    "mysql8":      "mysql",
    "mysql5":      "mysql",
}

_FUNCTION_NOTES: Dict[str, str] = {
    "DATE_FORMAT":    "MySQL DATE_FORMAT(d, fmt) → openGauss TO_CHAR(d, fmt)。格式符需适配: %Y→YYYY, %m→MM, %d→DD, %H→HH24, %i→MI, %s→SS。",
    "IFNULL":         "MySQL IFNULL(x, y) → openGauss COALESCE(x, y)。语义一致,可多参 COALESCE(x,y,z,…)。",
    "ISNULL":         "MySQL ISNULL(x) → openGauss (x IS NULL)。注意返回类型: MySQL 返 0/1, PG 返 boolean。",
    "GROUP_CONCAT":   "MySQL GROUP_CONCAT(c SEPARATOR ',') → openGauss STRING_AGG(c, ',')。DISTINCT/ORDER BY 子句位置不同。",
    "JSON_EXTRACT":   "MySQL JSON_EXTRACT(j, '$.k') → openGauss j -> 'k' (返 jsonb) 或 j ->> 'k' (返 text)。",
    "JSON_UNQUOTE":   "MySQL JSON_UNQUOTE(JSON_EXTRACT(j, '$.k')) → openGauss j ->> 'k'。",
    "FROM_UNIXTIME":  "MySQL FROM_UNIXTIME(t) → openGauss TO_TIMESTAMP(t)。",
    "UNIX_TIMESTAMP": "MySQL UNIX_TIMESTAMP(t) → openGauss EXTRACT(EPOCH FROM t)::bigint。",
    "CURDATE":        "MySQL CURDATE() → openGauss CURRENT_DATE。",
    "CONVERT_TZ":     "MySQL CONVERT_TZ → openGauss AT TIME ZONE。",
    "DATEDIFF":       "MySQL DATEDIFF(a, b) → openGauss (a::date - b::date)。返回类型不同。",
    "TIMESTAMPDIFF":  "MySQL TIMESTAMPDIFF(MINUTE, a, b) → openGauss EXTRACT(EPOCH FROM b - a)/60。",
    "AUTO_INCREMENT": "MySQL AUTO_INCREMENT → openGauss SERIAL / BIGSERIAL 或 GENERATED BY DEFAULT AS IDENTITY。",
    "FULLTEXT":       "MySQL FULLTEXT INDEX / MATCH AGAINST → openGauss tsvector + GIN + to_tsquery (需重设计)。",
}


def normalize_dialect(d: Optional[str]) -> str:
    """把 openGauss 等别名归一为 sqlglot 能识别的方言名。"""
    if not d:
        return "mysql"
    k = d.strip()
    return _DIALECT_ALIAS.get(k, _DIALECT_ALIAS.get(k.lower(), k.lower()))


def transpile_one(
    sql: str,
    source: str = "mysql",
    target: str = "postgres",
    pretty: bool = True,
) -> str:
    """单句 SQL 转译。失败抛 ParseError 交上层处理。"""
    src = normalize_dialect(source)
    tgt = normalize_dialect(target)
    results = sqlglot.transpile(sql, read=src, write=tgt, pretty=pretty)
    if not results:
        return sql
    return results[0]


def transpile_batch(
    sqls: List[str],
    source: str = "mysql",
    target: str = "postgres",
) -> List[Dict[str, Any]]:
    """批量转译。不抛错, 逐条 ok=true/false + error 记录。"""
    out: List[Dict[str, Any]] = []
    src = normalize_dialect(source)
    tgt = normalize_dialect(target)
    for i, s in enumerate(sqls):
        try:
            t = transpile_one(s, src, tgt)
            out.append({
                "index": i,
                "ok": True,
                "source": s,
                "target": t,
                "source_dialect": src,
                "target_dialect": tgt,
            })
        except ParseError as e:
            out.append({"index": i, "ok": False, "source": s, "error": f"parse error: {e}"})
        except Exception as e:  # noqa: BLE001
            out.append({"index": i, "ok": False, "source": s, "error": f"unexpected: {e}"})
    return out


def _detect_notes(sql: str) -> List[Dict[str, str]]:
    """探测原 SQL 中存在哪些需要说明的 MySQL 函数。简单 substring 匹配避免误报。"""
    if not sql:
        return []
    upper = sql.upper()
    compact = upper.replace(" ", "")
    notes: List[Dict[str, str]] = []
    for keyword, note in _FUNCTION_NOTES.items():
        if keyword == "AUTO_INCREMENT":
            if "AUTO_INCREMENT" in upper:
                notes.append({"keyword": keyword, "note": note})
            continue
        if keyword == "FULLTEXT":
            if "FULLTEXT" in upper or "MATCH(" in compact:
                notes.append({"keyword": keyword, "note": note})
            continue
        # 默认: 函数名( 探测
        if keyword + "(" in compact:
            notes.append({"keyword": keyword, "note": note})
    if "`" in sql:
        notes.append({"keyword": "BACKTICK", "note": "MySQL 反引号标识符 → openGauss 双引号标识符, sqlglot 自动替换。"})
    return notes


def explain_transpile(
    sql: str,
    source: str = "mysql",
    target: str = "postgres",
) -> Dict[str, Any]:
    """转译并返回原/后 SQL + 中文变动说明。供 SQL Diff 面板 / 验证脚本模板 使用。"""
    src = normalize_dialect(source)
    tgt = normalize_dialect(target)
    try:
        transpiled = transpile_one(sql, src, tgt, pretty=True)
    except ParseError as e:
        return {
            "ok": False,
            "error": f"parse error: {e}",
            "source": sql,
            "source_dialect": src,
            "target_dialect": tgt,
        }
    except Exception as e:  # noqa: BLE001
        return {
            "ok": False,
            "error": f"unexpected: {e}",
            "source": sql,
            "source_dialect": src,
            "target_dialect": tgt,
        }
    return {
        "ok": True,
        "source": sql,
        "target": transpiled,
        "source_dialect": src,
        "target_dialect": tgt,
        "notes": _detect_notes(sql),
        "sqlglot_version": sqlglot.__version__,
    }
