apiVersion: v1
kind: Service
metadata:
  name: zhiqian-rag
  labels:
    app.kubernetes.io/name: rag
    app.kubernetes.io/component: retrieval
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: rag
    app.kubernetes.io/component: retrieval
